# The federated identity for our user pool to auth with
CognitoIdentityPool:
  Type: AWS::Cognito::IdentityPool
  Properties:
    # Generate a name based on the stage
    IdentityPoolName: ${self:custom.stage}IdentityPool
    # Don't allow unathenticated users
    AllowUnauthenticatedIdentities: false
    # Link to our User Pool
    CognitoIdentityProviders:
      - ClientId:
          Ref: CognitoUserPoolClient
        ProviderName:
          Fn::GetAtt: [ "CognitoUserPool", "ProviderName" ]